### ISSUE TITLE
test issues...

### ISSUE THREAD

**Issue by faassen** [twillis/webobtoolkit#11]
How does one run the tests? It would be good to have some docs for it.

I tried:

```
$ python setup.py test
```

first I found out I had to have installed pytest, so I made a virtualenv as a subdir and installed pytest, but:
- the virtualenv should not be in the same directory (otherwise it starts running setuptools tests..)
- even if I put the virtualenv somewhere else, I get this:

```
DEBUG:/home/faassen/projects/webobtoolkit/tests/test_quickstart.py:yay I got an error
Traceback (most recent call last):
  File "/home/faassen/projects/webobtoolkit/tests/test_quickstart.py", line 174, in testCustomClient
...
  File "/home/faassen/projects/dummyenv/lib/python2.7/site-packages/webob/client.py", line 94, in __call__
    path, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 958, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python2.7/httplib.py", line 992, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python2.7/httplib.py", line 954, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python2.7/httplib.py", line 814, in _send_output
    self.send(msg)
  File "/usr/lib64/python2.7/httplib.py", line 776, in send
    self.connect()
  File "/usr/lib64/python2.7/httplib.py", line 757, in connect
    self.timeout, self.source_address)
  File "/usr/lib64/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno -5] No address associated with hostname
```

with a large traceback.

I also get enormous amounts of debug output before that I don't know how to interpret.

I tried to run the tests using pytest so I could isolate the failure. I found it eventually in the pytest docs, but the command is:

```
pip install -e .
```

to make the tests import webobtoolkit. (I usually use buildout so I don't have to use this).

I still get a lot of debugging output.

Looking at the code I get the impression that the test is _supposed_ to fail and give 'yay I got an error'.. If so that test badly needs to be rewritten to actually catch an exception, i.e. with pytest.raises().

Also is that test really dependent on httpbin.org? And are other tests dependent on example.com? I'd have expected the tests to mock things.

**Comment by twillis** [comment]
actually I think you were seeing a failing test that I ran into and fixed. 

https://github.com/twillis/webobtoolkit/commit/b61c44dbe3f6b0c4936cb09c5278785b2df3340f#diff-bb796028130d642a6923b8165c95568bL179

when all tests pass you dont see any output other than what is provided by py.test

as far as running the tests, i follow what I believe to be the way that pyramid taught me which is to create a virtualenv for development, run setup.py develop and then pip install whatever else you need. I usually put packages I'm working on in ./src and then I would run the tests from ./src/webobtoolkit/ 

so...

cd ~/project.env/src/webobtoolkit ; ../../bin/py.test
