### ISSUE TITLE
documentation confusion

### ISSUE THREAD

**Issue by faassen** [twillis/webobtoolkit#12]
I see a 'doc' directory with new sphinx documents in there, but I don't see where they are online. Are these docs up to date? Unfinished? What's their status?

In addition, the rst docs as uploaded to pypi have a RST error somewhere, as they don't render as rst on pypi. You can check the error by doing this:

```
python setup.py  --long-description | rst2html > out
```

You'll get a ton of warnings and also one error on line 68.

**Comment by faassen** [comment]
Oh no wonder you get an error; you are uploading markdown to pypi, not rst. So this is intentional. Perhaps just convert it to rst? github will still understand it.

**Comment by twillis** [comment]
hey @faassen , I never could get a good workflow down for generating the docs and where to put them. so I think it is fair to say the docs are unfinished. I think this was mainly due to me not knowing exactly who the audience should be. Do they understand HTTP? wsgi? webob? etc...  I could really use some help and suggestions in this area actually.

**Comment by faassen** [comment]
For a place to host the docs I strongly recommend readthedocs.org. It can automatically analyze the git repo and build sphinx docs from it.

Concerning the contents, I think you can assume the users will know webob well enough already, and will understand aspects of WSGI and HTTP. You can always be thorough and extra explicit in tutorial style content, but it's not a requirement.

**Comment by twillis** [comment]
ok thanks for sharing your thoughts on this. it's much appreciated.  actual docs hosted somewhere would probably be a good reason to release a 0.5. I had some other things I wanted to get in eventually so maybe it's sprint time. 

I also caught your blog today, thanks for the name drop :)

**Comment by twillis** [comment]
rtd's are here now. http://webob-toolkit.readthedocs.org/en/latest/ closing
