### ISSUE TITLE
Catching `ValueError` on `decode_content`?

### ISSUE THREAD

**Issue by workmanw** [twillis/webobtoolkit#14]
What would you think about catching a `ValueError` inside of the `decode_content`
([...webobtoolkit/filters.py#L76-L94](https://github.com/twillis/webobtoolkit/blob/master/webobtoolkit/filters.py#L76-L94))?

We've been running into an issue with a popular webserver returning "UTF-8" as the "Content-Encoding", which is not a valid value for that header, but it ultimately causes webob to throw a `ValueError` exception ([...webob/response.py#L971-L988](https://github.com/Pylons/webob/blob/master/webob/response.py#L971-L988)). 

This leaves us really with no option read the response when this happens. We could opt out of using webobtookit's decoder altogether and use our own that does catch that exception. 

I wanted to get your input, it seems like it'd be a positive thing to make webobtoolkit resilient enough to handle this, but I don't see a good option.

**Comment by twillis** [comment]
webob must have grown a decode content or somehow i missed it. so yeah I think this is a good move.

**Comment by workmanw** [comment]
Okay, pull request coming. Here is an example of this issue:

```
curl -I "http://www.wikihow.com/images/c/cf/Instantly-Brighten-Your-Smile-with-Listerine-and-Hydrogen-Peroxide-Step-4.jpg"

HTTP/1.1 200 OK
Content-Encoding: UTF-8
Last-Modified: Sat, 02 Nov 2013 11:01:43 GMT
ETag: "deb3249a774d2d5ab9005fe2d73459b1"
Content-Type: image/jpeg
Content-Length: 4416129
Accept-Ranges: bytes
Date: Tue, 20 May 2014 12:22:11 GMT
Connection: keep-alive
X-C: cache-d45-DAL,M
Cache-Control: s-maxage=15552000, max-age=15552000
```

**Comment by workmanw** [comment]
Resolved by merge. Thanks.

**Comment by twillis** [comment]
OK, it's in release 0.2.4 which is in pypi now so you should be good to go. thanks for the contribution. We'll do beers at dingle sometime. :+1:

**Comment by workmanw** [comment]
Thanks!! We'll likely be at dingle this Friday (last few fridays have been hectic). We can sync up out of band later.

**Comment by twillis** [comment]
Happy to help. I'll be in chicago until tuesday. hopefully next friday I can swing by.
